@extends('admin.layout')

@section('admin-title') Invitation Keys @endsection

@section('admin-content')
{!! breadcrumbs(['Admin Panel' => 'admin', 'Invitation Keys' => 'admin/invitations']) !!}

<h1>Invitation Keys</h1>

<p>Invitation keys can be used to register an account when the site is closed for registration (see the setting "is_registration_open" in <a href="{{ url('admin/settings') }}">Site Settings</a>). Users will be able to register by entering the code that is generated with the key. Generated invitations can be deleted only if they have not been used.</p>

{!! Form::open(['url' => 'admin/invitations/create', 'class' => 'text-right mb-3']) !!}
    {!! Form::submit('Generate New Invitation', ['class' => 'btn btn-primary']) !!}
{!! Form::close() !!}
@if(!count($invitations))
    <p>No invitations found.</p>
@else
    {!! $invitations->render() !!}
    <div class="mb-4 logs-table">
        <div class="logs-table-header">
            <div class="row">
                <div class="col-6 col-md-2"><div class="logs-table-cell">Code</div></div>
                <div class="col-6 col-md-2"><div class="logs-table-cell">Generated by</div></div>
                <div class="col-6 col-md-2"><div class="logs-table-cell">Used by</div></div>
                <div class="col-6 col-md-2"><div class="logs-table-cell">Used on</div></div>
                <div class="col-6 col-md-3"><div class="logs-table-cell">Created</div></div>
            </div>
        </div>
        <div class="logs-table-body">
            @foreach($invitations as $invitation)
                <div class="logs-table-row">
                    <div class="row flex-wrap">
                        <div class="col-6 col-md-2"><div class="logs-table-cell">{{ $invitation->code }}</div></div>
                        <div class="col-6 col-md-2"><div class="logs-table-cell">{!! $invitation->user->displayName !!}</div></div>
                        <div class="col-6 col-md-2"><div class="logs-table-cell">@if($invitation->recipient_id) {!! $invitation->recipient->displayName !!} @else --- @endif</div></div>
                        <div class="col-6 col-md-2"><div class="logs-table-cell">@if($invitation->created_at != $invitation->updated_at) {!! pretty_date($invitation->updated_at) !!} @else --- @endif</div></div>
                        <div class="col-6 col-md-3"><div class="logs-table-cell">{!! pretty_date($invitation->created_at,false) !!}</div></div>
                        <div class="col-6 col-md-1">
                            <div class="logs-table-cell">
                                @if(!$invitation->recipient_id)
                                    {!! Form::open(['url' => 'admin/invitations/delete/'.$invitation->id]) !!}
                                        {!! Form::submit('Delete', ['class' => 'btn btn-danger  py-0 px-1']) !!}
                                    {!! Form::close() !!}
                                @endif
                            </div>
                        </div>
                    </div>
                </div>
            @endforeach
        </div>
    </div>
    {!! $invitations->render() !!}
    <div class="text-center mt-4 small text-muted">{{ $invitations->total() }} result{{ $invitations->total() == 1 ? '' : 's' }} found.</div>
@endif

@endsection
